using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace Gloobster.SocialLogin.Facebook.Communication
{
	//generated by: http://json2csharp.com/

	[DataContract]
	public class LocationFO
	{
		[DataMember(Name = "city")]
		public string City { get; set; }
		[DataMember(Name = "country")]
		public string Country { get; set; }
		[DataMember(Name = "latitude")]
		public double Latitude { get; set; }
		[DataMember(Name = "longitude")]
		public double Longitude { get; set; }
		[DataMember(Name = "street")]
		public string Street { get; set; }
		[DataMember(Name = "zip")]
		public string Zip { get; set; }
		[DataMember(Name = "located_in")]
		public string LocatedIn { get; set; }
	}

	[DataContract]
	public class PlaceFO
	{
		[DataMember(Name = "id")]
		public string Id { get; set; }
		[DataMember(Name = "location")]
		public LocationFO Location { get; set; }
		[DataMember(Name = "name")]
		public string Name { get; set; }
	}

	[DataContract]
	public class DatumFO
	{
		[DataMember(Name = "id")]
		public string Id { get; set; }
		[DataMember(Name = "created_time")]
		public string CreatedTime { get; set; }
		[DataMember(Name = "place")]
		public PlaceFO Place { get; set; }
	}

	[DataContract]
	public class CursorsFO
	{
		[DataMember(Name = "before")]
		public string Before { get; set; }
		[DataMember(Name = "after")]
		public string After { get; set; }
	}

	[DataContract]
	public class PagingFO
	{
		[DataMember(Name = "cursors")]
		public CursorsFO Cursors { get; set; }
		[DataMember(Name = "next")]
		public string Next { get; set; }
	}

	[DataContract]
	public class TaggedPlacesFO
	{
		[DataMember(Name = "data")]
		public DatumFO[] Data { get; set; }
		[DataMember(Name = "paging")]
		public PagingFO Paging { get; set; }
	}


}
